version: '3.3'

services:
  afyass-mediator:
    container_name: afyass-mediator
    build:
      context: ./afyass-mediator

  tulonge-mediator:
    container_name: tulonge-mediator
    build:
      context: ./tulonge-mediator

networks:
  default:
    external:
      name: dpod-network

volumes:
  mongo-data:
